# Config for cargo-dist
[dist]
cargo-dist-version = "0.28.0"
rust-toolchain-version = "1.85.0"
ci = ["github"]
installers = ["shell", "powershell"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-pc-windows-msvc"]
pr-run-mode = "plan"
