[package]
name = "ferronote-store"
version = "1.2.5"
edition = "2024"
authors = ["Tareq M Y"]
description = "Note storage backend for Ferronote"
license = "MIT"
repository = "https://github.com/tareqmy/ferronote"
readme = "README.md"

[dependencies]
color-eyre = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
zip = "2.2"
